name: Build React App
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Node.js and NPM
      - name: Install Node.js and NPM
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "18.x"

      # Install dependencies and build application
      - name: Install dependencies and build application
        run: |
          cd client
          npm install
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
